[package]
name = "calc"
version = "0.1.0"
authors = ["Сухарик <65870+suhr@users.noreply.github.com>"]
edition = "2018"
publish = false

[dependencies]
sana = { path = "../../sana" }
lalrpop-util = "0.19.0"
rustyline = "6.2.0"

[build-dependencies]
lalrpop = "0.19.0"
