[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2018"
license = "MIT"

[dev-dependencies]
sana = { version = "0.1.0", path = "../sana" }

[[example]]
name = "json"
path = "json/main.rs"
