name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Clippy
      run: cargo clippy

  bench:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      name: Download baseline
      continue-on-error: true
      with:
        name: master-baseline
        path: sana/target/criterion
    - name: Run benchmarks
      continue-on-error: true
      run: cd sana && cargo bench -- --noplot --load-baseline new --baseline master
    - name: Save baseline
      if: ${{ github.ref == 'master' }}
      run: cargo bench -- --noplot --save-baseline master
    - uses: actions/upload-artifact@v2
      if: ${{ github.ref == 'master' }}
      with:
        name: master-baseline
        path: sana/target/criterion
